DROP TABLE IF EXISTS gh_pull_requests;
DROP TABLE IF EXISTS gh_issues;
DROP TABLE IF EXISTS gh_repos;
DROP TABLE IF EXISTS gh_users;

CREATE TABLE IF NOT EXISTS gh_users (
    user_id UUID PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    bio TEXT,
    location VARCHAR(255),
    plan VARCHAR(20) NOT NULL CHECK (plan IN ('free', 'pro', 'enterprise'))
);

CREATE TABLE IF NOT EXISTS gh_repos (
    repo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL,
    repo_name VARCHAR(255) NOT NULL,
    description TEXT,
    language VARCHAR(50),
    is_private BOOLEAN NOT NULL DEFAULT FALSE,
    stars_count INTEGER NOT NULL DEFAULT 0,
    forks_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_repos_owner
        FOREIGN KEY (owner_id) REFERENCES gh_users(user_id)
);

CREATE TABLE IF NOT EXISTS gh_issues (
    issue_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id INTEGER NOT NULL,
    author_id UUID NOT NULL,
    title VARCHAR(500) NOT NULL,
    body TEXT,
    state VARCHAR(20) NOT NULL CHECK (state IN ('open', 'closed')),
    label VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    closed_at TIMESTAMP,
    CONSTRAINT fk_issues_repo
        FOREIGN KEY (repo_id) REFERENCES gh_repos(repo_id),
    CONSTRAINT fk_issues_author
        FOREIGN KEY (author_id) REFERENCES gh_users(user_id)
);

CREATE TABLE IF NOT EXISTS gh_pull_requests (
    pr_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id INTEGER NOT NULL,
    author_id UUID NOT NULL,
    title VARCHAR(500) NOT NULL,
    body TEXT,
    state VARCHAR(20) NOT NULL CHECK (state IN ('open', 'closed', 'merged')),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    closed_at TIMESTAMP,
    merged_at TIMESTAMP,
    CONSTRAINT fk_prs_repo
        FOREIGN KEY (repo_id) REFERENCES gh_repos(repo_id),
    CONSTRAINT fk_prs_author
        FOREIGN KEY (author_id) REFERENCES gh_users(user_id)
);
